### ISSUE TITLE
bug in Pisot number test?

### ISSUE THREAD

**Issue by drewitz** [rgugliel/CoxIter#13]
For the [3,5,3] orthoscheme, CoxIter says the growth rate is a Salem number but _not_ a Pisot number. This is not possible and afaik, it is indeed both:

```
$ ./coxiter < ../graphs/simplices/3-jkrt_347-02-J3.coxiter 
Reading graph: 
	Number of vertices: 4
	Dimension: 3
	Vertices: 1, 2, 3, 4
	Field generated by the entries of the Gram matrix: Q[sqrt(5)]
File read

Finding connected subgraphs......
Finding graphs products......
Computations......
	Computation time: 0.00967261s

Information
	Cocompact: yes
	Finite covolume: yes
	f-vector: (4, 6, 4, 1)
	Number of vertices at infinity: 0
	Alternating sum of the components of the f-vector: 2
	Euler characteristic: 0
	Signature (numerically): 3,1,0

Growth series: 
f(x) = C(2,2,2,3,6,10)/(1 - 2 * x + x^2 - x^4 + 2 * x^5 - 2 * x^6 + x^7 - x^9 + 2 * x^10 - x^11)

Growth rate: 1.3509803377162373102114035730633264361
	Perron number: yes
	Pisot number: no
	Salem number: yes
```

**Comment by rgugliel** [comment]
I'll look into this, hopefully later on this week.

Thanks for raising this issue.

**Comment by rgugliel** [comment]
Hey Simon,
So we have the minimal polynomial of the growth rate which is 
```
x^10 - x^9 - x^6 + x^5 - x^4 - x + 1
```
The repartition of its roots is the following:

- lambda =~ 1.35098
- its inverse =~ 0.74
- 6 complex roots

If I'm not mistaken, all the complex roots lie on the unit circle and not inside (reason why it is a Salem number but not a Pisot number).

What do you think?

**Comment by drewitz** [comment]
Hi Rafael,
yes, you're right.
I had learned a wrong "definition" of Pisot numbers which implied that every Salem number is a Pisot number and trusted the source so that I didn't double check the definition.
Sorry about that.
