### ISSUE TITLE
Install problems on macOS

### ISSUE THREAD

**Issue by drewitz** [rgugliel/CoxIter#15]
When installing pari `brew install homebrew/x11/pari` fails because homebrew/x11 is deprecated and empty.

When compiling, `gmpxx.h` cannot be found.

**Comment by rgugliel** [comment]
Following my email, this does not really solve the issue. Keeping open.

**Comment by drewitz** [comment]
will be solved by #20 and #21

**Comment by rgugliel** [comment]
Merged, should be fine.
