### ISSUE TITLE
False positive for finite volume test

### ISSUE THREAD

**Issue by sashakolpakov** [rgugliel/CoxIter#22]
Polytope diagram (colour code: red=3, green=8, grey=dotted edge):
<a href="https://imgbb.com/"><img src="https://i.ibb.co/94CQTN0/d18-2.png" alt="d18-2" border="0"></a>

CoxIter input file (vertex indices +1 compared to the diagram): 
> 24 18
vertices labels: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
1 14 3
1 20 3
1 24 3
2 16 3
2 23 3
3 16 3
3 17 3
3 22 3
4 15 8
4 18 3
4 19 3
5 10 3
5 11 3
6 11 3
6 12 3
7 8 3
7 14 3
8 12 3
8 13 8
9 13 1
9 15 1
9 20 8
9 23 8
10 23 3
11 21 3
13 15 1
13 22 8
15 21 8
17 19 3
18 24 3

CoxIter output: 
> Sashas-MacBook-Pro:coxiter sasha$ ./coxiter < d18_2.coxiter 
Reading graph: 
	Number of vertices: 24
	Dimension: 18
	Vertices: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24
	Field generated by the entries of the Gram matrix: ?
File read
Finding connected subgraphs......
Finding graphs products......
Computations......
	Computation time: 44.8369s
Information
	Cocompact: no
	**Finite covolume: yes**
	f-vector: (823, 7512, 35340, 111678, 262104, 480396, 706811, 847383, 833748, 674447, 447471, 241944, 105468, 36465, 9759, 1948, 273, 24, 1)
	Number of vertices at infinity: 4
	Alternating sum of the components of the f-vector: 0
	Euler characteristic: -109638854849/22600997906614761553920000
	Covolume: pi^9 * 109638854849/1521127719312789804023808000000

Issue: this polytope cannot have finite covolume.  Its Coxeter diagram contains a disjoint union of two affine \tilde{E}_8 sub-diagrams (11, 5, 10, 4, 9, 22, 1, 15, 20) and (6, 13, 0, 23, 17, 3, 18, 16, 19). Their common orthogonal complement is the single edge (12,21). The latter is an elliptic sub-diagram. However, the orthogonal complement of an affine sub-diagram cannot be elliptic (it should be also affine, otherwise there is no finite-volume cusp with the property).

**Comment by sashakolpakov** [comment]
@drewitz, @rgugliel : please, contact me by email for more info or more test examples.

**Comment by rgugliel** [comment]
Hey Sasha!
Thanks for opening the two issues. I don't have a lot of time for CoxIter these days but I'll try to have a look.

Cheers.

**Comment by sashakolpakov** [comment]
@drewitz, @rgugliel : If you replace the green edges in the diagram above (i.e. all edges with label 8) with \infty-edges (i.e. by bold edges), then you get an actual Coxeter diagram for some finite-volume polytope in H^{18} (not known at the time to Kaplinskaya and Vinberg).  This one passes the finite-volume test in CoxIter (and it should!)

**Comment by rgugliel** [comment]
Hello @sashakolpakov ,
I'm wondering whether the above diagram corresponds to an hyperbolic Coxeter group.
According to Matthieu, the signature of the Gram matrix is not (18, 1, 5): you can see that by consider the following equation:
Reduce[Det[G[[3 ;; 22, 3 ;; 22]]] == 0 && 0 == Det[G[[2 ;; 21, 2 ;; 21]]]]

Can you keep me updated?

Thanks.

**Comment by sashakolpakov** [comment]
@rgugliel : This is not a hyperbolic Coxeter group (above = in the initial post). But CoxIter identifies it as such (which is why I claimed "false positive"). The one with the changed colour code "red = pi/3 angle, green = 0 angle, grey = common perpendicular (should be dotted)" should be Ok. I think I falsely described the colour code in my previous post. Sorry :-)

**Comment by sashakolpakov** [comment]
I took the diagram from my initial post, and used another colour code: "green" -- zero angle, "grey" -- dotted edge, "red" -- pi/3.  By using SageMath I computed the eigenvalues of the matrix in question: 

> [-5.319533644619737?,
>  0,
>  0,
>  0,
>  0,
>  0,
>  0.3742968230177789?,
>  0.50000000000000000?,
>  0.5573840559382009?,
>  0.5573840559382009?,
>  1,
>  1,
>  1.170174712838487?,
>  1.170174712838487?,
>  1.202201347703642?,
>  1.5000000000000000?,
>  1.634855179510917?,
>  1.696037527243352?,
>  1.696037527243352?,
>  2,
>  2,
>  2.108180294387398?,
>  4.576403703979960?,
>  4.576403703979960?]
> 

Looks good to me. Some dotted edge lengths are necessary to get this computation done (which I did not provide).

**Comment by rgugliel** [comment]
@sashakolpakov Can you provide the dotted edge length, please?

**Comment by sashakolpakov** [comment]
@rgugliel : all have length \ell such that cosh(\ell) = 3 (the respective element of the Gram matrix is -3, according to what I got from SageMath)

**Comment by rgugliel** [comment]
@sashakolpakov When exporting the above initial graph from CoxIter and replacing the 3*2 corresponding entries in the Gram matrix by -3, I find signature (20, 2, 2).

In order to proceed forward, please provide the Gram matrix you considered (with the same ordering as the graph you posted above).

**Comment by sashakolpakov** [comment]
@rgugliel: Just a reminder: below is the correct example with correct signature that has to pass the finite volume test by Coxeter. The initial example is _not_ finite volume (for the reasons described in the initial posting), but it passes the test for me. 

I just wonder: what kind of software have you used for signature computation? I used SageMath, which goes to (what I believe to be) a BLAS eigenvalues routine. 

1) Diagram: (indexed from 0 to 23)

![diag_18_2](https://user-images.githubusercontent.com/5302373/74843841-cc54d700-532c-11ea-80a9-b0d5ff73e1c3.png)


2) Gram matrix: (indexed from 0 to 23)

[(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1/2, 0, 0, 0, 0, 0, -1/2, 0, 0, 0, -1/2),
(0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1/2, 0, 0, 0, 0, 0, 0, -1/2, 0),
(0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1/2, -1/2, 0, 0, 0, 0, -1/2, 0, 0),
(0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, -1/2, -1/2, 0, 0, 0, 0, 0),
(0, 0, 0, 0, 1, 0, 0, 0, 0, -1/2, -1/2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(0, 0, 0, 0, 0, 1, 0, 0, 0, 0, -1/2, -1/2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(0, 0, 0, 0, 0, 0, 1, -1/2, 0, 0, 0, 0, 0, -1/2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(0, 0, 0, 0, 0, 0, -1/2, 1, 0, 0, 0, -1/2, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, -3, 0, -3, 0, 0, 0, 0, -1, 0, 0, -1, 0),
(0, 0, 0, 0, -1/2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1/2, 0),
(0, 0, 0, 0, -1/2, -1/2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1/2, 0, 0, 0),
(0, 0, 0, 0, 0, -1/2, 0, -1/2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(0, 0, 0, 0, 0, 0, 0, -1, -3, 0, 0, 0, 1, 0, -3, 0, 0, 0, 0, 0, 0, -1, 0, 0),
(-1/2, 0, 0, 0, 0, 0, -1/2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(0, 0, 0, -1, 0, 0, 0, 0, -3, 0, 0, 0, -3, 0, 1, 0, 0, 0, 0, 0, -1, 0, 0, 0),
(0, -1/2, -1/2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0),
(0, 0, -1/2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, -1/2, 0, 0, 0, 0, 0),
(0, 0, 0, -1/2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1/2),
(0, 0, 0, -1/2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1/2, 0, 1, 0, 0, 0, 0, 0),
(-1/2, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0),
(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1/2, 0, 0, 0, -1, 0, 0, 0, 0, 0, 1, 0, 0, 0),
(0, 0, -1/2, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0),
(0, -1/2, 0, 0, 0, 0, 0, 0, -1, -1/2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0),
(-1/2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1/2, 0, 0, 0, 0, 0, 1)]

3) Eigenvalues: 
[-5.319533644619737?,
 0,
 0,
 0,
 0,
 0,
 0.3742968230177789?,
 0.50000000000000000?,
 0.5573840559382009?,
 0.5573840559382009?,
 1,
 1,
 1.170174712838487?,
 1.170174712838487?,
 1.202201347703642?,
 1.5000000000000000?,
 1.634855179510917?,
 1.696037527243352?,
 1.696037527243352?,
 2,
 2,
 2.108180294387398?,
 4.576403703979960?,
 4.576403703979960?]

**Comment by rgugliel** [comment]
We used Mathematica.
In the graph you give at the beginning there are weights 8. I the above snippet, I don't see them; it seems they are replaced by some -1.

**Comment by sashakolpakov** [comment]
@rgugliel : Ok, one more time. I think some kind of miscommunication takes place. 

> Just a reminder: below is the correct example with correct signature that has to pass the finite >volume test by Coxeter. The initial example is not finite volume (for the reasons described in the > initial posting), ...

So the example above (example A) for which I supplied the diagram + Gram matrix + eigenvalues is correct. It has no \pi/8 angles, but angles of 0 instead. It colour code is "green" -- zero angle, "grey" -- dotted edge, "red" -- pi/3. Example A should pass the finite volume test. This is true positive. 

If we use another colour code, "green" -- pi/8, "grey" -- dotted edge, "red" -- pi/3, then we get another example (example B, from which I started). In example B, there is a problem: its Coxeter diagram contains a disjoint union of two affine \tilde{E}_8 sub-diagrams (11, 5, 10, 4, 9, 22, 1, 15, 20) and (6, 13, 0, 23, 17, 3, 18, 16, 19). Their common orthogonal complement is the single edge (12,21). The latter is an elliptic sub-diagram. However, the orthogonal complement of an affine sub-diagram cannot be elliptic (it should be also affine, otherwise there is no finite-volume cusp with the property).

I have no idea what goes wrong with example B, and why CoxIter says it has finite volume. I know for sure that it does not (see above). I never computed the Gram matrix for it, nor its signature.

**Comment by rgugliel** [comment]
If I'm not mistaken, example B is not hyperbolic. As such, any answer from CoxIter cannot be trusted (the hyperbolicity assumption is absolutely necessary).

**Comment by sashakolpakov** [comment]
Aha, I did not know about this! Somehow I assumed that CoxIter runs a signature pre-check, and would at least give a warning.

**Comment by rgugliel** [comment]
That would be nice! However, it is quite difficult: to compute the signature, you need the full Gram matrix, and for that you need the values of the dotted edges.

As far as I know, there are some partial criteria to exclude hyperbolicity, but no full test.

I may update the documentation that make that more clear.

**Comment by sashakolpakov** [comment]
@rgugliel, @drewitz : as I noted in the initial posting, each affine diagram should have an affine orthogonal complement. This could be some kind of a pre-check + signature if no common perpendiculars present. However, this is just an idea for the future. Thanks for the info!

**Comment by rgugliel** [comment]
Yes, of course, you are right. As mentioned, I don't really have time to do further developments to CoxIter. However, it is opensource, so anyone can open a PR to add new features. I'll be happy to provide support and review it. Cheers.
