### ISSUE TITLE
False negative for finite volume test

### ISSUE THREAD

**Issue by sashakolpakov** [rgugliel/CoxIter#23]
Polytope's Coxeter diagram (colour code: red=3, blue=4):

<a href="https://imgbb.com/"><img src="https://i.ibb.co/7YkK3NH/d13-10.png" alt="d13-10" border="0"></a>

This polytope is known to me to have finite volume, since it is a 13-dimensional face of the 21-dimensional Borcherds polytope. It is obtained by successive projections of its normals to hyperplanes of its faces, and this computation has been verified. 

CoxIter tries to enhance the elliptic sub-diagram below (edge):

<a href="https://imgbb.com/"><img src="https://i.ibb.co/VV2DXMv/d13-10-0.png" alt="d13-10-0" border="0"></a>

It reports that it succeeds to enhance it in **3** ways, and therefore the polytope is not finite volume. 

1st enhancement to an affine (ideal vertex) sub-diagram:

<a href="https://imgbb.com/"><img src="https://i.ibb.co/y5M0HvD/d13-10-1.png" alt="d13-10-1" border="0"></a>

2nd enhancement to an affine (ideal vertex) sub-diagram:

<a href="https://imgbb.com/"><img src="https://i.ibb.co/1dYRBct/d13-10-2.png" alt="d13-10-2" border="0"></a>

3rd enhancement: here we have 3 \tilde{F}_4 diagrams with overlaps, which does not give us an affine sub-diagram. 

<a href="https://imgbb.com/"><img src="https://i.ibb.co/fCj091q/d13-10-3.png" alt="d13-10-3" border="0"></a>

Seemingly, there is no difference made between a union of subgraphs and an induced subgraph isomorphic to 3 disjoint \tilde{F}_4's. 

Here are the input file for CoxIter, and the output in "debug" mode (all vertices are indexed +1 in CoxIter files): [download link](https://www.dropbox.com/sh/d8969pjguiau17u/AAC236d048OI62BnOS9s2F97a?dl=0).

**Comment by rgugliel** [comment]
@sashakolpakov Can you include here the CoxIter file? The download link is not valid anymore.

**Comment by sashakolpakov** [comment]
@rgugliel Please check [this link](https://www.dropbox.com/sh/d8969pjguiau17u/AAC236d048OI62BnOS9s2F97a?dl=0). The test examples that I use all come as facets of the 21-dimensional Borcherds polytope. They are computed in SageMath using (pretty basic) linear algebra. It is known that they are finite-volume, and I think my computation of their normals / Coxeter diagrams is correct (I tested same code on smaller polytopes, and it worked fine, and also I got correct results when using CoxIter on them).

**Comment by rgugliel-da** [comment]
Closing this issue as I don't have material to reproduce

**Comment by rgugliel** [comment]
Closing this issue, as I don't have material to reproduce.
